name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v3

    - name: Patch Submodule Compilation Error
      run: |
        ((Get-Content ext/blackbone/src/BlackBone/Process/ProcessModules.cpp -Raw).Replace('modName->ptr<std::decay_t<decltype(ustr)>::type>()', 'modName->ptr<typename std::decay_t<decltype(ustr)>::type>()')) | Set-Content ext/blackbone/src/BlackBone/Process/ProcessModules.cpp
      shell: powershell

    - name: Build Solution
      run: msbuild Xenos.sln /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v145 /m

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: Xenos64
        path: build/x64/Release/Xenos64.exe
