name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [Win32, x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild Xenos.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /m
